
ALTER TABLE public.projects
  ADD COLUMN IF NOT EXISTS occupancy_growth_rate NUMERIC DEFAULT 5,
  ADD COLUMN IF NOT EXISTS tax_rate NUMERIC DEFAULT 35,
  ADD COLUMN IF NOT EXISTS residual_asset_rate NUMERIC DEFAULT 40;
